config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only: [:create, :show, :destroy] do
    resources :themes, only: [:create]
  end
  resources :themes, only: [:show, :destroy] do
    resources :questions, only: [:create]
  end
  resources :questions, only: [:show, :destroy] do
    resources :tabs, only: [:create]
    resources :comments, only: [:create]
    resources :solutions, only: [:create]
    resources :outputs, only: [:create]
    resources :links, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :solutions, only: [:destroy]
  resources :outputs, only: [:destroy]
  resources :tabs, only: [:destroy]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :theme
  has_many :tabs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :solutions, dependent: :destroy
  has_many :outputs, dependent: :destroy
  #has_many :links, dependent: :destroy
  validates :subject, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: [:show, :destroy]
  def show
    @tab = Tab.new
    @comment = Comment.new
    @solution = Solution.new
    @output = Output.new
    @all_solution = all_solution
    @first_tab_id = first_tab_id
  end

  def create
    @theme = Theme.find(params[:theme_id])
    @category = @theme.category
    @question = Question.new(question_params)
    @question.theme = @theme
    if @question.save
      redirect_to category_path(@category)
    else
      render 'categories/show'
    end
  end

  def destroy
    @question.destroy
    redirect_to category_path(@question.theme.category)
  end

  # find all comments solutions and outputs for a question and sort by order
  def all_solution
    all_solution = []
    comments = Comment.where(question: @question)
    solutions = Solution.where(question: @question)
    outputs = Output.where(question: @question)
    push_elements_in_array(all_solution, comments)
    push_elements_in_array(all_solution, solutions)
    push_elements_in_array(all_solution, outputs)
    all_solution.sort_by(&:order)
  end

  def push_elements_in_array(array, elements)
    elements.each do |element|
      array.push(element)
    end
  end

  def first_tab_id
    Tab.where(question: @question).minimum('id') unless @question.tabs == []
  end

  def filter_solution_by_tab(tab)
    @all_solution.filter do |solution|
      solution.tab == tab
    end
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:subject)
  end
end

app/views/questions/show.html.erb
<div class="container-application-mt">
  <!-- Category name and Theme name -->
  <div class='link-category'>
    <%= link_to category_path(@question.theme.category) do %>
      <%= @question.theme.category.name.capitalize %>/<%= @question.theme.name.capitalize %>
    <% end %>
  </div>

  <!-- Question -->
  <h1><%= @question.subject.capitalize %></h1>

  <!-- tabs -->
  <!-- tab buttons -->
  <ul class="nav nav-tabs">
    <% unless @question.tabs == [] %>
      <% @question.tabs.each do |tab| %>
        <% if @question.tabs.first == tab %>
          <li class="nav-item tab-position">
            <a class="nav-link tab-language active" data-toggle="tab" href="#<%= tab.name.parameterize %>" data-name='<%= tab.name.parameterize %>' data-id='<%= tab.id %>'><%= tab.name %></a>
            <%= link_to tab_path(tab),
                  method: :delete, class: "delete-tab-trash" do %>
                  <i class="fas fa-trash-alt"></i>
                 <% end %>
          </li>
        <% else %>
          <li class="nav-item tab-position">
            <a class="nav-link tab-language" data-toggle="tab" href="#<%= tab.name.parameterize %>" data-name='<%= tab.name.parameterize %>' data-id='<%= tab.id %>'><%= tab.name %></a>
          </li>
        <% end %>
      <% end %>
    <% end %>
    <li class="nav-item">
      <a class="nav-link tab-language" data-toggle="tab" href="#new-tab"><i class="fas fa-plus"></i> Add a tab</a>
    </li>
  </ul>

  <!-- flex tab content and add btns -->
  <div class="tabs-and-add-buttons-container d-flex">
    <!--  tabs content -->
    <div class="tab-content tabs-content-container">
      <!-- form for adding new tabs -->
      <div class="for-tabs card-tab tab-pane fade" id='new-tab'>
        <!-- add new tab -->
        <%= simple_form_for([@question, @tab]) do |f| %>
          <%= f.input :name, placeholder: 'Tab name', label: false, class: 'ml-3' %>
          <%= f.submit "New Tab", class: "btn btn-outline-primary" %>
        <% end %>
      </div>
      <% if @question.tabs != [] %>
        <% @question.tabs.each do |tab|  %>
          <% if @question.tabs.first == tab %>
            <div class="for-tabs card-tab tab-pane fade show active" id='<%= tab.name.parameterize %>'>
          <% else %>
            <div class="for-tabs card-tab tab-pane fade" id='<%= tab.name.parameterize %>'>
          <% end %>
          <% all_solution = @all_solution.select do |solution| %>
            <% solution.tab == tab %>
          <% end %>
          <% all_solution.each do |solution| %>
            <% if solution.respond_to?('comment') %>
              <div class="card-comment"><%= solution.comment %>
                <%= link_to comment_path(solution),
                  method: :delete, class: "delete-comment-trash" do %>
                  <i class="fas fa-trash-alt"></i>
                 <% end %>
              </div>
            <% elsif solution.respond_to?('solution') %>
              <div class='card-solution background-black'><%= solution.solution %>
                <%= link_to solution_path(solution),
                  method: :delete, class: "delete-solution-trash" do %>
                  <i class="fas fa-trash-alt"></i>
                 <% end %>
              </div>
            <% else %>
              <div class='card-solution background-grey'><%= solution.output %>
                <%= link_to output_path(solution),
                  method: :delete, class: "delete-comment-trash" do %>
                  <i class="fas fa-trash-alt"></i>
                 <% end %>
              </div>
            <% end %>
          <% end %>
          </div>
        <% end %>
      <% else %>
        <% unless @all_solution == [] %>
          <div class="for-tabs card-tab">
            <% @all_solution.each do |solution| %>
              <% if solution.respond_to?('comment') %>
                <div class="card-comment"><%= solution.comment %>
                  <%= link_to comment_path(solution),
                    method: :delete, class: "delete-comment-trash" do %>
                    <i class="fas fa-trash-alt"></i>
                 <% end %>
                </div>
              <% elsif solution.respond_to?('solution') %>
                <div class="card-solution background-black"><%= solution.solution %>
                  <%= link_to solution_path(solution),
                    method: :delete, class: "delete-solution-trash" do %>
                    <i class="fas fa-trash-alt"></i>
                 <% end %>
                </div>
              <% else %>
                <div class='card-solution background-grey'><%= solution.output %>
                  <%= link_to output_path(solution),
                    method: :delete, class: "delete-comment-trash" do %>
                    <i class="fas fa-trash-alt"></i>
                 <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>

    <!--  buttons add comment solution output-->
    <div class="add-btns-container">
      <ul class="nav flex-column nav-pills">
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#comment"><i class="fas fa-plus"></i> Add a comment</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#solution"><i class="fas fa-plus"></i> Add a solution</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#output"><i class="fas fa-plus"></i> Add an output</a>
        </li>
      </ul>
    </div>
  </div>


    <!-- content add buttons cso=comment solution output -->
    <div class="tab-content add-btns-content-container">
      <div class="for-add-cso card-tab tab-pane fade" id='comment'>
        <!-- add comment -->
        <%= simple_form_for([@question, @comment]) do |f| %>
          <% if @question.tabs != [] %>
            <div class="form-tab-id">
              <%= f.input :tab, :as => :hidden, input_html: {value: @first_tab_id}, class: 'replace-tab-id' %>
            </div>
          <% end %>
          <%= f.input :comment, placeholder: 'Write a comment', label: false, :input_html => {:rows => 4}, class: 'ml-3' %>
          <%= f.submit "New Comment", class: "btn btn-outline-primary" %>
        <% end %>
      </div>

      <div class="for-add-cso card-tab tab-pane fade" id='solution'>
        <!-- add solution -->
        <%= simple_form_for([@question, @solution]) do |f| %>
          <% if @question.tabs != [] %>
            <div class="form-tab-id">
              <%= f.input :tab, :as => :hidden, input_html: {value: @first_tab_id}, class: 'replace-tab-id' %>
            </div>
          <% end %>
          <%= f.input :solution, placeholder: 'Write a solution', label: false, :input_html => {:rows => 10}, class: 'ml-3' %>
          <%= f.submit "New Solution", class: "btn btn-outline-primary" %>
        <% end %>
      </div>

      <div class="for-add-cso card-tab tab-pane fade" id='output'>
        <!-- add output -->
        <%= simple_form_for([@question, @output]) do |f| %>
          <% if @question.tabs != [] %>
            <div class="form-tab-id">
              <%= f.input :tab, :as => :hidden, input_html: {value: @first_tab_id}, class: 'replace-tab-id' %>
            </div>
          <% end %>
          <%= f.input :output, placeholder: 'Output', label: false, :input_html => {:rows => 6}, class: 'ml-3' %>
          <%= f.submit "New Output", class: "btn btn-outline-primary" %>
        <% end %>
      </div>
    </div>
</div>
<!-- add link -->