config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only: [:create, :show, :destroy] do
    resources :themes, only: [:create]
  end
  resources :themes, only: [:show, :destroy] do
    resources :questions, only: [:create]
  end
  resources :questions, only: [:show, :destroy] do
    resources :tabs, only: [:create]
    resources :comments, only: [:create]
    resources :solutions, only: [:create]
    resources :outputs, only: [:create]
    resources :links, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :solutions, only: [:destroy]
  resources :outputs, only: [:destroy]
  resources :tabs, only: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :themes, dependent: :destroy
  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :destroy]

  def index
    @category = Category.new
    @categories = Category.where(user: current_user)
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user
    if @category.save
      redirect_to root_path
    else
      render 'categories/index'
    end
  end

  def show
    @theme = Theme.new
    @question = Question.new
    @themes = Theme.where(category: @category)
  end

  def destroy
    @category.destroy
    redirect_to root_path
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_form.html.erb
<%= simple_form_for (category), wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>
  <%= f.input :name, placeholder: 'Category name', label: false, class: 'ml-3' %>
  <%= f.submit "New Category", class: "btn btn-outline-primary" %>
<% end %>

app/views/categories/index.html.erb
<!-- render partial form -->
<% if current_user %>
  <div class="container-application-mt">
    <%= render 'form', category: @category %>

    <div class="cards-container">
      <div class="cards-grid">
        <% @categories.each do |category| %>
          <div class="card-category">
            <%= link_to category_path(category),
              method: :delete do %>
              <i class="fas fa-trash-alt delete-category-trash"></i>
            <% end %>
            <%= link_to category.name.capitalize, category_path(category), class: 'stretched-link' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/show.html.erb
<div class="d-flex">
  <!-- theme menu -->
  <div class="menu-container">
  <!-- category name -->
    <div class="menu-padding d-flex justify-content-between align-items-center">
      <h1 class='mb-0'><%= @category.name.capitalize %></h1>
      <!-- btn to create new theme -->
      <ul class="nav nav-pills">
        <li class="nav-item btn-plus">
          <a class="btn-plus-a btn-plus-theme nav-link" data-toggle="tab" href="add-theme"><i class="fas fa-plus-square"></i></a>
        </li>
      </ul>
    </div>
    <!-- form to create new theme -->
    <div class="tab-content">
      <div class="for-new-theme tab-background-theme card-tab tab-pane fade" id='add-theme'>
        <%= simple_form_for([@category, @theme]) do |f| %>
          <%= f.input :name, placeholder: 'Theme name', label: false, class: 'ml-3' %>
          <%= f.submit "New Theme", class: "btn btn-outline-primary" %>
        <% end %>
      </div>
    </div>

    <!-- all themes -->
    <ul class="nav flex-column nav-pills">
      <% @themes.each do |theme| %>
        <% if @themes.first == theme  %>
          <li class="nav-item theme-links">
            <%= link_to theme_path(theme),
              method: :delete do %>
              <i class="fas fa-trash-alt delete-theme-trash"></i>
            <% end %>
            <a class="btn-theme nav-link active" data-toggle="tab" href="#<%= theme.name.parameterize %>" data-id="theme.id"><%= theme.name.capitalize %></a>
          </li>
        <% else %>
          <li class="nav-item theme-links">
            <%= link_to theme_path(theme),
              method: :delete do %>
              <i class="fas fa-trash-alt delete-theme-trash"></i>
            <% end %>
            <a class="btn-theme nav-link" data-toggle="tab" href="#<%= theme.name.parameterize %>" data-id="theme.id"><%= theme.name.capitalize %></a>
          </li>
        <% end %>
      <% end %>
    </ul>

  </div>
  <!-- theme menu end -->

  <!-- questions -->
  <div class="tab-content container-questions">
    <% @themes.each do |theme| %>
      <% if theme.id == @themes.first.id %>
        <div class="container-theme-questions card-tab tab-pane fade show active" id='<%= theme.name.parameterize %>'>
      <% else %>
        <div class="container-theme-questions card-tab tab-pane fade" id='<%= theme.name.parameterize %>'>
      <% end %>
          <div class="container-content-theme-questions">
            <div class="d-flex justify-content-between">
              <h2 class="theme-name"><%= theme.name.capitalize %></h2>
              <!-- btn to create new question -->
              <ul class="nav nav-pills">
                <li class="nav-item btn-plus">
                  <a class="btn-plus-a btn-plus-question nav-link" data-toggle="tab" data-id="<%= theme.id %>" href="#add-question-<%= theme.id %>"><i class="fas fa-plus-square"></i></a>
                </li>
              </ul>
            </div>
            <!-- form to create new question -->
            <div class="tab-content">
              <div class="for-new-question tab-background-question card-tab tab-pane fade" id='add-question-<%= theme.id %>'>
                <%= simple_form_for([theme, @question]) do |f| %>
                  <%= f.input :subject, placeholder: 'How to ... ?', label: false, class: 'ml-3' %>
                  <%= f.submit "New Question", class: "btn btn-outline-primary" %>
                <% end %>
              </div>
            </div>
            <!-- displaying all questions -->
            <% theme.questions.each do |question| %>
              <div class="card-question">
                <%= link_to question_path(question),
                  method: :delete do %>
                  <i class="fas fa-trash-alt delete-question-trash"></i>
                <% end %>
                <%= link_to question_path(question) do %>
                  <h2><%= question.subject.capitalize %></h2>
                  <p>Last updated <%= question.updated_at %></p>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>

</div>